# Generated by Django 3.1.3 on 2020-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0002_discussion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.DateField(auto_now_add=True)),
                ('contact', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
