# Generated by Django 3.1.3 on 2020-11-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0005_forum_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
