# Generated by Django 3.1.3 on 2020-11-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0007_auto_20201127_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='userid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_forum.user_tab'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='userid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_forum.user_tab'),
        ),
    ]
